CRITICAL - 2023-01-31 23:52:02 --> Class 'App\Controllers\PegawaiModel' not found
#0 C:\xampp\htdocs\DhikaPegawai\vendor\codeigniter4\framework\system\CodeIgniter.php(809): App\Controllers\Pegawai->__construct()
#1 C:\xampp\htdocs\DhikaPegawai\vendor\codeigniter4\framework\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\htdocs\DhikaPegawai\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\DhikaPegawai\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\DhikaPegawai\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
CRITICAL - 2023-01-31 23:52:25 --> Class 'App\Controllers\PegawaiModel' not found
#0 C:\xampp\htdocs\DhikaPegawai\vendor\codeigniter4\framework\system\CodeIgniter.php(809): App\Controllers\Pegawai->__construct()
#1 C:\xampp\htdocs\DhikaPegawai\vendor\codeigniter4\framework\system\CodeIgniter.php(410): CodeIgniter\CodeIgniter->createController()
#2 C:\xampp\htdocs\DhikaPegawai\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#3 C:\xampp\htdocs\DhikaPegawai\public\index.php(37): CodeIgniter\CodeIgniter->run()
#4 C:\xampp\htdocs\DhikaPegawai\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#5 {main}
ERROR - 2023-01-31 23:52:39 --> Error connecting to the database: Access denied for user '****'@'localhost' (using password: YES)
CRITICAL - 2023-01-31 23:52:39 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
#0 C:\xampp\htdocs\DhikaPegawai\vendor\codeigniter4\framework\system\Database\BaseConnection.php(577): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\DhikaPegawai\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\DhikaPegawai\vendor\codeigniter4\framework\system\Model.php(183): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\DhikaPegawai\vendor\codeigniter4\framework\system\BaseModel.php(584): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\DhikaPegawai\app\Controllers\Pegawai.php(15): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\DhikaPegawai\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Pegawai->index()
#6 C:\xampp\htdocs\DhikaPegawai\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Pegawai))
#7 C:\xampp\htdocs\DhikaPegawai\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\DhikaPegawai\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\DhikaPegawai\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2023-01-31 23:52:39 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\DhikaPegawai\app\Views\errors\html\error_exception.php:96
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 96, Array)
#1 C:\xampp\htdocs\DhikaPegawai\app\Views\errors\html\error_exception.php(96): print_r(Object(App\Controllers\Pegawai), true)
#2 C:\xampp\htdocs\DhikaPegawai\vendor\codeigniter4\framework\system\Debug\Exceptions.php(234): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\DhikaPegawai\vendor\codeigniter4\framework\system\Debug\Exceptions.php(237): CodeIgniter\Debug\Exceptions->CodeIgniter\Debug\{closure}()
#4 C:\xampp\htdocs\DhikaPegawai\vendor\codeigniter4\framework\system\Debug\Exceptions.php(121): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#5 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
